version: '3.8'

services:
  python-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-flask-api
    volumes:
      - ./:/app
    ports:
      - "5050:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URI=postgresql://postgres:your_secure_password@postgres:5432/geodatabase
    networks:
      - default_network
    restart: unless-stopped

networks:
  default_network:
    driver: bridge
  